---
title: "Result comparison"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r setup}

suppressPackageStartupMessages(require(caret))
suppressPackageStartupMessages(require(dplyr))
suppressPackageStartupMessages(require(raster))
suppressPackageStartupMessages(require(sf))
suppressPackageStartupMessages(require(stars))
suppressPackageStartupMessages(require(xtable))

base_path <- "/home/alber/Documents/data/experiments/prodes_reproduction/papers/clouds"

source(file.path(base_path, "scripts", "util.R"))

# Shapefiles with the extent of the images.
landsat_scenes <- "/home/alber/Documents/data/experiments/prodes_reproduction/papers/clouds/data/masks/image_tiles/wrs2_asc_desc.dbf"
sentinel_tiles <- "/home/alber/Documents/data/experiments/prodes_reproduction/papers/clouds/data/masks/image_tiles/sentinel_2_index_shapefile.shp"
stopifnot(all(vapply(c(landsat_scenes, sentinel_tiles), file.exists, logical(1))))

# Match Sentinel to Landsat images.
sentinel2landsat <- match_scenes2tiles(tile_path = sentinel_tiles, 
                                       scene_path = landsat_scenes, 
                                       tiles = stringr::str_sub(c("T19LFK", "T21LXH", "T22MCA"), 2), 
                                       scenes = NULL) %>%
    dplyr::mutate(tile = stringr::str_c("T", tile),
                  path = stringr::str_sub(scene, 1, 3),
                  row  = stringr::str_sub(scene, 4, 6)) %>%
    tidyr::nest(scene = c("scene", "path", "row"))

```



```{r get_cloud_masks}

#---- Read cloud masks -----

baseline <- dir_name <- file_path <- img_date <- level <- processing <- NULL

fm4_s2cloud_tb <- base_path %>%
    file.path("data", "fmask4_s2cloudless") %>%
    list.dirs() %>%
    tibble::enframe(name = NULL) %>%
    dplyr::rename(file_path = "value") %>%
    dplyr::filter(endsWith(file_path, ".SAFE")) %>%
    dplyr::mutate(dir_name = tools::file_path_sans_ext(basename(file_path))) %>% 
    tidyr::separate(col = dir_name,
                    into = c("mission", "level", "img_date", "baseline",
                             "orbit", "tile", "processing"), sep = '_') %>%
    dplyr::mutate(fmask4 = purrr::map_chr(file_path, find_files, 
                                          pattern = "._Fmask4[.]tif$"),
                  s2cloudless = purrr::map_chr(file_path, find_files, 
                                               pattern = "._s2cloudless_mask[.]tif$")) %>%
    dplyr::select(-file_path, -baseline, -processing, -level) %>%
    ensurer::ensure_that(nrow(.) > 0,err_desc = "No images found")
fm4_s2cloud_tb %>%
    dplyr::filter(is.na(fmask4) | is.na(s2cloudless)) %>%
    print(n = Inf)

sen2cor_tb <- base_path %>%
    file.path("data", "sen2cor") %>%
    list.dirs() %>%
    tibble::enframe(name = NULL) %>%
    dplyr::rename(file_path = "value") %>%
    dplyr::filter(endsWith(file_path, ".SAFE")) %>%
    dplyr::mutate(dir_name = tools::file_path_sans_ext(basename(file_path))) %>% 
    tidyr::separate(col = dir_name,
                    into = c("mission", "level", "img_date", "baseline",
                             "orbit", "tile", "processing"), sep = '_') %>%
    dplyr::mutate(sen2cor = purrr::map_chr(file_path, find_files, 
                                          pattern = "(._SCL[.]tif$|._SCL_20m[.]jp2$)")) %>%
    dplyr::select(-file_path, -baseline, -processing) %>%
    ensurer::ensure_that(nrow(.) > 0,err_desc = "No images found")
sen2cor_tb %>%
    filter(is.na(sen2cor)) %>%
    print(n = Inf)

    
maja_tb <- base_path %>%
    file.path("data", "maja") %>%
    list.dirs() %>%
    tibble::enframe(name = NULL) %>%
    dplyr::rename(file_path = "value") %>%
    dplyr::filter(endsWith(file_path, ".SAFE")) %>%
    dplyr::mutate(dir_name = tools::file_path_sans_ext(basename(file_path))) %>% 
    tidyr::separate(col = dir_name,
                    into = c("mission", "level", "img_date", "baseline",
                             "orbit", "tile", "processing"), sep = '_') %>%
    dplyr::mutate(maja = purrr::map_chr(file_path, find_files, 
                                          pattern = "._CLM_R1[.]tif$")) %>%
    dplyr::select(-file_path, -baseline, -processing) %>%
    ensurer::ensure_that(nrow(.) > 0,err_desc = "No images found")    
maja_tb %>%
    dplyr::filter(is.na(maja)) %>%
    print(n = Inf)


#---- Join MAJA & SEN2COR ----
s2core_maja_tb <- maja_tb %>%
    dplyr::full_join(sen2cor_tb, by = c("mission", "level", "img_date", "tile", 
                                        "orbit"))
s2core_maja_tb %>%
    dplyr::filter(is.na(sen2cor) | is.na(maja)) %>%
    print(n = Inf)


#---- Join FAMSK4 & S2 CLOUDLESS to MAJA & SEN2COR ----
mission <- orbit <- tile <- fmask4 <- maja <- s2cloudless <- sen2cor <- NULL
fm4_s2cloud_maja_s2cor_tb <- fm4_s2cloud_tb %>% 
    dplyr::full_join(s2core_maja_tb, by = c("mission", "img_date", "tile", "orbit")) %>%
    dplyr::select(mission, orbit ,tile, img_date, fmask4, maja, sen2cor, s2cloudless) %>%
    dplyr::arrange(mission, tile, img_date)

#---- Spot duplicates ---
fm4_s2cloud_maja_s2cor_tb %>% 
    dplyr::group_by(mission, tile, img_date) %>% 
    dplyr::summarize(n = n()) %>%
    dplyr::filter(n > 1) %>%
    ensurer::ensure_that(nrow(.) == 0, err_desc = "Some images are duplicated!")

# Original number of images versus number of images with results for all clouds algothms
cloud_imgs <- fm4_s2cloud_maja_s2cor_tb %>% 
    dplyr::filter(mission == "S2A") %>%
    (function(x){
        print(sprintf("Total number of images: %s", nrow(x)))
        invisible(x)}
    ) %>%
    tidyr::drop_na() %>%
    (function(x){
        print(sprintf("Images with all the algorithms: %s", nrow(x)))
        invisible(x)
    })

# Images with missing algorithms    
fm4_s2cloud_maja_s2cor_tb %>%
    dplyr::filter(is.na(fmask4) | is.na(maja) | is.na(sen2cor) | is.na(s2cloudless)) %>%
    print(n = Inf)


cloud_mask_tb <- fm4_s2cloud_maja_s2cor_tb %>%
    tidyr::drop_na() %>%
    dplyr::select(-c(mission, orbit)) %>%
    dplyr::mutate(fmask4_r      = purrr::map(fmask4,       raster::raster),
                  maja_r        = purrr::map(maja,         raster::raster),
                  sen2cor_r     = purrr::map(sen2cor,      raster::raster),
                  s2cloudless_r = purrr::map(s2cloudless,  raster::raster)) %>%
    dplyr::select(-c(fmask4, maja, sen2cor, s2cloudless))

expert <- NULL
cloud_imgs <- cloud_imgs %>%
    # Images selected for sampling.
    # TODO: The experts classified points, not images. Move this to some other place.
    dplyr::mutate(expert = dplyr::case_when(mission == "S2A" & tile =="T19LFK" & img_date == "20170102T144722" ~ "Anderson",
                                            mission == "S2A" & tile =="T19LFK" & img_date == "20180507T144731" ~ "Suli",
                                            mission == "S2A" & tile =="T19LFK" & img_date == "20180527T144731" ~ "Anderson",
                                            mission == "S2A" & tile =="T19LFK" & img_date == "20181103T144731" ~ "Anderson",
                                            mission == "S2A" & tile =="T21LXH" & img_date == "20170328T140051" ~ "Suli",
                                            mission == "S2A" & tile =="T21LXH" & img_date == "20170616T140051" ~ "Michel",
                                            mission == "S2A" & tile =="T21LXH" & img_date == "20170706T140051" ~ "Michel",
                                            mission == "S2A" & tile =="T21LXH" & img_date == "20180611T140051" ~ "Suli",
                                            mission == "S2A" & tile =="T21LXH" & img_date == "20180621T140051" ~ "Suli",
                                            mission == "S2A" & tile =="T21LXH" & img_date == "20180919T140051" ~ "Suli",
                                            mission == "S2A" & tile =="T21LXH" & img_date == "20181009T140051" ~ "Michel",
                                            mission == "S2A" & tile =="T22MCA" & img_date == "20170603T135111" ~ "Michelle",
                                            mission == "S2A" & tile =="T22MCA" & img_date == "20170623T135111" ~ "Suli",
                                            mission == "S2A" & tile =="T22MCA" & img_date == "20180419T135111" ~ "Michelle",
                                            mission == "S2A" & tile =="T22MCA" & img_date == "20180628T135111" ~ "Michelle")) %>%
    dplyr::select(mission, orbit, tile, img_date, expert, fmask4, maja, sen2cor, s2cloudless) %>%
    print(n = Inf)

```





```{r get_data_masks}

#---- Urban mask. ----
file_name <- NULL
urban_tb <- base_path %>%
    file.path("data", "masks", "urban", "tiled") %>%
    list.files(pattern = "[.]tif$", full.names = TRUE) %>%
    tibble::enframe(name = NULL) %>%
    dplyr::rename(file_path = value) %>%
    dplyr::mutate(file_name = tools::file_path_sans_ext(basename(file_path)),
                  urban_r = purrr::map(file_path, raster::raster)) %>%
    tidyr::separate(col = file_name, into = c(NA, NA, "tile"))  %>%
    dplyr::mutate(tile = stringr::str_to_upper(tile)) %>%
    dplyr::select(-file_path)

#---- Water mask. ----
water_tb <- base_path %>%
    file.path("data", "masks", "water", "tiled") %>%
    list.files(pattern = "[.]tif$", full.names = TRUE) %>%
    tibble::enframe(name = NULL) %>%
    dplyr::rename(file_path = value) %>%
    dplyr::mutate(file_name = tools::file_path_sans_ext(basename(file_path)),
                  water_r = purrr::map(file_path, raster::raster)) %>%
    tidyr::separate(col = file_name, into = c(NA, "tile")) %>%
    dplyr::mutate(tile = stringr::str_to_upper(tile)) %>%
    dplyr::select(-file_path)

#---- PRODES mask. ----
prodes_tb <- base_path %>%
    file.path("data", "masks", "prodes", "tiled") %>%
    list.files(pattern = "[.]shp$", full.names = TRUE) %>%
    ensurer::ensure_that(length(.) > 0, err_desc = "Shapefiles not found!") %>%
    tibble::enframe(name = NULL) %>%
    dplyr::rename(file_path = value) %>%
    dplyr::mutate(file_name = tools::file_path_sans_ext(basename(file_path)),
                  prodes = purrr::map(file_path, sf::read_sf)) %>%
    tidyr::separate(col = file_name, into = c(NA, NA, NA, "path", "row"), 
                    sep = '_') %>%
    dplyr::select(-file_path)

```


```{r get_expert_samples}

#---- Shapefiles of clouds. ----

# Read the sample point classified by experts.
cloud_experts <- base_path %>%
    file.path("data", "samples", "point") %>%
    list.files(pattern = "[.]shp$", full.names = TRUE) %>%
    ensurer::ensure_that(length(.) > 0, err_desc = "No shapefiles found!") %>%
    tibble::enframe(name = NULL) %>%
    dplyr::rename(file_path = value) %>%
    dplyr::mutate(file_name = tools::file_path_sans_ext(basename(file_path))) %>%
    tidyr::separate(col = file_name, into = c("mission", "level", "tile", NA, 
                                              "img_date")) %>%
    dplyr::filter((mission == "S2A" & tile == "T19LFK" & img_date %in% c("20161004T144732", "20170102T144722", "20180507T144731", "20181103T144731")) |
                  (mission == "S2A" & tile == "T21LXH" & img_date %in% c("20170328T140051", "20180611T140051", "20180919T140051", "20181009T140051")) | 
                  (mission == "S2A" & tile == "T22MCA" & img_date %in% c("20170603T135111", "20170623T135111", "20180419T135111", "20180628T135111"))) %>% 
    dplyr::mutate(samples_sf = purrr::map(file_path, read_samples),
                  n_samples = purrr::map_int(samples_sf, nrow),
                  srs = purrr::map(samples_sf, sf::st_crs)) %>%
    dplyr::left_join(sentinel2landsat, by = "tile") %>%
    dplyr::mutate(prodes_merged = purrr::map(scene, merge_prodes_scenes, 
                                             prodes_tb = prodes_tb, srs = NULL)) %>%
    # Get the values for the samples.
    # NOTE: DO NOT change the order in which the columns are added, otherwise update
    # the function rename_samples.
    dplyr::mutate(samples_sf = purrr::map2(samples_sf, prodes_merged, get_label, 
                                              polygon_var = class_name)) %>%
    dplyr::left_join(water_tb, by = "tile") %>%
    dplyr::mutate(samples_sf = purrr::map2(samples_sf, water_r, get_label_raster)) %>%
    dplyr::left_join(urban_tb, by = "tile") %>%
    dplyr::mutate(samples_sf = purrr::map2(samples_sf, urban_r, get_label_raster)) %>%
    dplyr::inner_join(cloud_mask_tb, by = c("tile", "img_date")) %>%
    # NOTE: Do NOT merge the mutates.
    dplyr::mutate(samples_sf = purrr::map2(samples_sf, fmask4_r,      get_label_raster)) %>%
    dplyr::mutate(samples_sf = purrr::map2(samples_sf, maja_r,        get_label_raster)) %>%
    dplyr::mutate(samples_sf = purrr::map2(samples_sf, sen2cor_r,     get_label_raster)) %>%
    dplyr::mutate(samples_sf = purrr::map2(samples_sf, s2cloudless_r, get_label_raster)) %>%
    dplyr::mutate(samples_sf = purrr::map(samples_sf, rename_samples)) %>%
    # Recode.
    dplyr::mutate(samples_sf = purrr::map(samples_sf, recode_sf_prodes,      coded_var = prodes),
                  samples_sf = purrr::map(samples_sf, recode_sf_water,       coded_var = water),
                  samples_sf = purrr::map(samples_sf, recode_sf_urban,       coded_var = urban),
                  samples_sf = purrr::map(samples_sf, recode_sf_fmask4,      coded_var = fmask4),
                  samples_sf = purrr::map(samples_sf, recode_sf_maja,        coded_var = maja),
                  samples_sf = purrr::map(samples_sf, recode_sf_sen2cor,     coded_var = sen2cor),
                  samples_sf = purrr::map(samples_sf, recode_sf_s2cloudless, coded_var = s2cloudless)) %>%
    # Compute the frequency of each class in each image.
    dplyr::mutate(fmask4_freq      = purrr::map(fmask4_r,      get_raster_freq, detector = fmask4),
                  maja_freq        = purrr::map(maja_r,        get_raster_freq, detector = maja),
                  s2cloudless_freq = purrr::map(s2cloudless_r, get_raster_freq, detector = s2cloudless),
                  sen2cor_freq     = purrr::map(sen2cor_r,     get_raster_freq, detector = sen2cor))


saveRDS(cloud_experts, file = "/home/alber/Documents/data/experiments/prodes_reproduction/papers/clouds/data/cloud_experts.rds")
cloud_experts <- readRDS(cloud_experts, file = "/home/alber/Documents/data/experiments/prodes_reproduction/papers/clouds/data/cloud_experts.rds")


recode_vec <- c("cirrus" = "cloud", 
                "clear"  = "clear", 
                "cloud"  = "cloud", 
                "shadow" = "shadow")

FID <- samples_sf <- samples_tb <- NULL
prodes <- water <- urban <- NULL
data_tb <- cloud_experts %>%
    dplyr::select(mission, level, tile, img_date, samples_sf) %>%
    dplyr::mutate(samples_tb = purrr::map(samples_sf, sf::st_set_geometry, 
                                          value = NULL)) %>%
    dplyr::select(-samples_sf) %>%
    tidyr::unnest(cols = c(samples_tb)) %>%
    dplyr::select(-FID) %>%
    tidyr::drop_na() %>%
    tibble::as_tibble() %>%
    dplyr::mutate(land_cover = dplyr::case_when(urban ~ "urban",
                                                water ~ "water",
                                                TRUE  ~ prodes)) %>%
    dplyr::select(-c(prodes, water, urban)) %>%
    dplyr::mutate(expert      = dplyr::recode(expert,      !!!recode_vec),
                  fmask4      = dplyr::recode(fmask4,      !!!recode_vec),
                  maja        = dplyr::recode(maja,        !!!recode_vec),
                  s2cloudless = dplyr::recode(s2cloudless, !!!recode_vec),
                  sen2cor     = dplyr::recode(sen2cor,     !!!recode_vec))

```



```{r plot_images}

fmask4_freq <- maja_freq <- s2cloudless_freq <- sen2cor_freq <- NULL
img_freq <- cloud_experts %>%
    dplyr::select(tile, img_date, fmask4 = fmask4_freq, maja = maja_freq, 
                  s2cloud = s2cloudless_freq, sen2cor = sen2cor_freq)

fmask4_img_freq  <- img_freq %>% format_freq(fmask4)
sen2cor_img_freq <- img_freq %>% format_freq(sen2cor)
maja_img_freq    <- img_freq %>% 
    format_freq(maja) %>% 
    dplyr::mutate(total = total/4) # compensate for images' spatial resolutions
s2cloud_img_freq <- img_freq %>% 
    format_freq(s2cloud) %>% 
    dplyr::mutate(total = total * 9) # compensate for images' spatial resolutions

img_freq <- dplyr::bind_rows(fmask4_img_freq, maja_img_freq, 
                             s2cloud_img_freq, sen2cor_img_freq)


plot_tb <- img_freq %>% 
    tidyr::drop_na() %>%
    dplyr::mutate(img_date = stringr::str_sub(img_date, 1, 8)) %>% 
    dplyr::mutate(label = dplyr::recode(label,
                                        "cirrus" = "0_cirrus",
                                        "cloud"  = "1_cloud",
                                        "clear"  = "2_clear",
                                        "shadow" = "3_shadow"))

#---- Plot images using historgram ----
png(width = 960, height = 960, pointsize = 24, 
    filename = file.path(base_path, "tex", "images", 
                         "pixels_by_detector_v3.png"))
# Get the tiles and properties for each plot,
img_freq %>%
    dplyr::pull(tile) %>%
    unique() %>%
    sort() %>% 
    tibble::enframe(name = NULL) %>%
    dplyr::rename(my_tile = value) %>%
    dplyr::mutate(row_id = dplyr::row_number(),
                  my_legend = FALSE,
                  my_xlabel = FALSE,
                  my_ylabel = ifelse(row_id == 1, TRUE, FALSE),
                  repeat_n  = ifelse(row_id == nrow(.), 2, 1)) %>% 
    # repat the last row to get only the legend
    tidyr::uncount(repeat_n) %>% 
    dplyr::mutate(row_id = dplyr::row_number(),
                  my_legend = ifelse(row_id == nrow(.), TRUE, FALSE),
                  only_legend = ifelse(row_id == nrow(.), TRUE, FALSE)) %>% 
    dplyr::mutate(tile_plot = purrr::pmap(dplyr::select(., my_tile, my_legend, 
                                                        my_xlabel, my_ylabel, 
                                                        only_legend), 
                                          function(my_tile, my_legend, 
                                                   my_xlabel, my_ylabel, 
                                                   only_legend, plot_tb){
                                              plot_tb %>% 
                                                  dplyr::filter(tile == my_tile) %>% 
                                                  plot_image_pixels(title = sprintf(msg, my_tile), 
                                                                    legend = my_legend, 
                                                                    xlabel = my_xlabel, 
                                                                    ylabel = my_ylabel, 
                                                                    only_legend = only_legend) %>% 
                                                  return()
                                          }, plot_tb = plot_tb)) %>%
    dplyr::pull(tile_plot) %>% 
    {multiplot(plotlist = ., file = "deleteme", cols = 4, 
               layout = matrix(c(1, 1, 2, 2, 3, 3, 4), nrow = 1, byrow = TRUE))}
dev.off()

```



```{r print_img_accuracy}

# summary of accuracies for each tile, image and detector.
data_tb %>%
    dplyr::select(tile, img_date) %>% 
    dplyr::distinct() %>% 
    dplyr::mutate(conmat = purrr::map2(tile, img_date, function(my_tile, my_img_date){
        data_tb %>% 
            dplyr::filter(tile == my_tile, img_date == my_img_date) %>% 
            format_conmat() %>% 
            return()
    })) %>% 
    {for (r in 1:nrow(.)) {
        r <- dplyr::slice(., r)
        print(sprintf("accucary for image %s %s.", r$tile, r$img_date))
        print(r$conmat)
    }}

# summary of accuracies for each tile, and detector.
conmat <- NULL
data_tb %>%
    dplyr::select(tile) %>% 
    dplyr::distinct() %>% 
    dplyr::mutate(conmat = purrr::map(tile, function(my_tile){
        data_tb %>% 
            dplyr::filter(tile == my_tile) %>% 
            format_conmat() %>% 
            return()
    })) %>% 
    tidyr::unnest(cols = c(conmat)) %>% 
    table_to_latex(out_file = file.path(base_path, "tex", "tables", "user_producer_accuracy_tile.tex"),
                   caption_msg = "User and producer accuracies for each tile and cloud-detection algorithm.") %>% 
    View()
    print(n = Inf)

# Summary of accuracies for each detector.
print("Total accuracy.")
data_tb %>%
    format_conmat() %>% 
    table_to_latex(out_file = file.path(base_path, "tex", "tables", "user_producer_accuracy.tex"),
                   caption_msg = "User and producer accuracies for each cloud-detection algorithm.") %>% 
    print(n = Inf)

```


```{r print_img_accuracy_area}


stop("Unfinished!")

print("Total accuracy weighted by area.")

# NOTE: Use Fmask4 areas as reference.
areas_tb <- cloud_experts %>% 
    dplyr::select(tile, img_date, fmask4_r, fmask4_freq) %>% 
    dplyr::mutate(y_resolution = purrr::map_dbl(fmask4_r, raster::yres),
                  label_area = purrr::map2(fmask4_freq, y_resolution, 
                                           function(freq_tb, yres){
                                               freq_tb <- freq_tb %>% 
                                                   dplyr::mutate(total = total * yres * yres) %>% 
                                                   dplyr::mutate(total = ifelse(total == 0, NA, total)) %>% 
                                                   tidyr::drop_na()
                                               res <- freq_tb %>% 
                                                   dplyr::pull(total) %>% 
                                                   magrittr::set_names(dplyr::pull(freq_tb, label))
                                               if (!("clear" %in% names(res))) 
                                                   res <- c(res, "clear" = 0)
                                               if (!("cloud" %in% names(res))) 
                                                   res <- c(res, "cloud" = 0)
                                               if (!("shadow" %in% names(res))) 
                                                   res <- c(res, "shadow" = 0)
                                               return(res)
                                           })) %>% 
    dplyr::select(-fmask4_freq, -fmask4_r, -y_resolution)



format_conmat_area <- function(.data, area_vec){
    expert <- fmask4 <- maja <- s2cloudless <- sen2cor <- NULL
    
    fmask4_acc <- .data %>% 
        get_confusion_matrix(prediction_var = fmask4, reference_var = expert) %>% 
        magrittr::extract2("table") %>% 
        asses_accuracy_area(label_areas = area_vec) %>% 
        magrittr::set_names(c(names(.)[1], paste0("fmask4_", names(.)[-1])))
    maja_acc <- .data %>% 
        get_confusion_matrix(prediction_var = maja, reference_var = expert) %>% 
        magrittr::extract2("table") %>% 
        asses_accuracy_area(label_areas = area_vec) %>% 
        magrittr::set_names(c(names(.)[1], paste0("maja_", names(.)[-1])))
    s2cloud_acc <- .data %>% 
        get_confusion_matrix(prediction_var = s2cloudless, reference_var = expert) %>% 
        magrittr::extract2("table") %>% 
        asses_accuracy_area(label_areas = area_vec) %>% 
        magrittr::set_names(c(names(.)[1], paste0("s2cloudless_", names(.)[-1])))
    sen2cor_acc <- .data %>% 
        get_confusion_matrix(prediction_var = sen2cor, reference_var = expert) %>% 
        magrittr::extract2("table") %>% 
        asses_accuracy_area(label_areas = area_vec) %>% 
        magrittr::set_names(c(names(.)[1], paste0("sen2cor_", names(.)[-1])))

    fmask4_acc %>% 
        dplyr::left_join(maja_acc, by = "label") %>% 
        dplyr::left_join(s2cloud_acc, by = "label") %>% 
        dplyr::left_join(sen2cor_acc, by = "label") %>% 
    return()
}

total_area <- do.call(rbind, areas_tb$label_area) %>% 
    colSums()
data_tb %>%
    format_conmat_area(area_vec = total_area) %>% 
    View()


```






```{r TODO_print_summary_table_michelle_style}

# TODO: write format_accuracy_alt in such a way that allows a table like:
# DATE  DETECTOR      CLOUD      CLEAR        SHADOW
#                    ua  pa oa   ua  pa oa     ua  pa oa

```





